/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './src/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
    './screens/**/*.{js,jsx,ts,tsx}',
    './App.{js,jsx,ts,tsx}',
  ],

  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        bg: '#FFFFFF',
        canvas: '#F4F4F0',
        ink: '#0A0A0A',
        ink2: '#6B6B6B',
        ink3: '#AAAAAA',
        placeholder: '#C0C0C0',
        brand: '#1A6B4A',
        'brand-light': '#E8F5EE',
        line: '#E8E8E8',
        divider: '#F0F0F0',
        'row-divider': '#F5F5F5',
        input: '#F5F5F5',
        'input-readonly': '#F0F0F0',
        danger: '#E53E3E',
        'danger-bg': '#FEE2E2',
        rating: '#F5A623',
        'dock-surface': 'rgba(18, 18, 18, 0.78)',
        'placeholder-image': '#D8DDD6',
        // KYC status palette
        warn: '#B45309',
        'warn-bg': '#FFF3E0',
        success: '#22C55E',
        'success-bg': '#DCFCE7',
        'success-dark': '#15803D',
      },
      fontFamily: {
        display: ['DMSerifDisplay_400Regular'],
        sans: ['DMSans_400Regular'],
        medium: ['DMSans_500Medium'],
        semibold: ['DMSans_600SemiBold'],
        bold: ['DMSans_700Bold'],
      },
      fontSize: {
        h1: ['26px'],
        h2: ['22px'],
        h3: ['18px'],
        body: ['15px'],
        'body-sm': ['13px'],
        caption: ['12px'],
        label: ['11px'],
        micro: ['10px'],
      },
      borderRadius: {
        sm: '8px',
        md: '10px',
        lg: '12px',
        card: '14px',
        hero: '20px',
        pill: '999px',
      },
      spacing: {
        'screen-h': '24px',
        'card-pad': '16px',
        'section-gap': '20px',
        'input-h': '56px',
        'button-h': '56px',
        'dock-h': '72px',
        'dock-w': '312px',
        'header-h': '56px',
      },
    },
  },
  plugins: [],
};
